server.port:
  8081
server.tomcat.uri-encoding:
  utf-8
  #MySQL
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.url:
  jdbc:mysql://39.106.231.83:3306/jw?characterEncoding=utf8&amp;useSSL=false
spring.datasource.username:
  jw
spring.datasource.password:
  root
  #Spring Data JPA
spring.jpa.database:
  MYSQL
spring.jpa.show-sql:
  true
spring.jpa.hibernate.ddl-auto:
  update
  # Naming strategy
spring.jpa.hibernate.naming-strategy:
  org.hibernate.cfg.ImprovedNamingStrategy
  # stripped before adding them to the entity manager)
spring.jpa.properties.hibernate.dialect:
  org.hibernate.dialect.MySQL5Dialect
  #加载Mybatis配置文件
mybatis.mapper-locations:
  classpath:mapper/*Mapper.xml
mybatis.type-aliases-package:
  com.recharge.componet.dataobject
thymeleaf:
  cache: false
  prefix: classpath:/templates/
  suffix: .html
  encoding: UTF-8
  servlet:
    content-type: text/html
  mode: HTML5

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

